export const FriendlyEventNames = {
"Register":"Name Registered",
"Moved":"Moved",
"Sold":"Sold",
"SoldAuction":"Sold at auction",
"ForSale":"Listed for sale",
"ForAuction":"Listed for auction",
"DirectOfferRejected":"Offer rejected",
"AuctionCanceled":"Auction Cancelled",
"AuctionCanceledReservePrice":"Failed to meet reserve",
"AuctionStarted":"Auction started",
"AuctionBid":"New bid",
"DirectOffer":"New offer",
"DirectOfferCanceled":"Offer cancelled",
"WithdrawnSale":"Withdrawn from sale",
"WithdrawnAuction":"Withdrawn from auction",
"price3":"500",
"price4":"100",
"price5":"5",

}